### ISSUE TITLE
Mainnet/Devnet do not work: from_bytes>SizeMismatch

### ISSUE THREAD

**Issue by JakkuSakura** [drift-labs/gateway#32]
When I execute this command, it panicks: `from_bytes>SizeMismatch`
`drift-gateway 'https://api.devnet.solana.com' --emulate 777tRS4e6i19zwmF9JKiBe1jWg3kwcc8nUzMVdVFKF8k --dev`

**Comment by jordy25519** [comment]
likely issue from upstream dep being updated.
please try latest [v0.1.11](https://github.com/drift-labs/gateway/releases/tag/v0.1.11)

**Comment by JakkuSakura** [comment]
Hi, I tried v0.1.11 but doesn't work. It seems to be an upstream error https://github.com/drift-labs/protocol-v2/issues/891

**Comment by jordy25519** [comment]
which rust version and OS are you using? are there any firewalls etc.
I'm unable to reproduce this so far..

**Comment by JakkuSakura** [comment]
I use MacOS and archlinux. 
info: The currently active `rustc` version is `rustc 1.78.0-nightly (a84bb95a1 2024-02-13)`

**Comment by JakkuSakura** [comment]
upstream error

**Comment by enachb** [comment]
I had the same issue and was able to pin point the problem:

Compiling it with Rust 1.76.0 results in a working binary. However the compiled binary with a newer Rust 1.77.2  yields this error.

Please note that this was tested on 2 separate machines having the same outcome.
