### ISSUE TITLE
websocket error

### ISSUE THREAD

**Issue by dzovani** [drift-labs/gateway#53]
getting this even with older versions, periodically, always need to restart as service

May 07 22:33:44 Ubuntu-2204-jammy-amd64-base drift-gateway[2799880]: [2024-05-07T22:33:44Z WARN  gateway] event stream finished: 0, sending close
May 07 22:33:44 Ubuntu-2204-jammy-amd64-base drift-gateway[2799880]: [2024-05-07T22:33:44Z WARN  gateway] event stream finished: 0, sending close
May 07 22:34:00 Ubuntu-2204-jammy-amd64-base drift-gateway[2799880]: [2024-05-07T22:34:00Z WARN  gateway] event stream finished: 0, sending close
May 07 22:34:13 Ubuntu-2204-jammy-amd64-base drift-gateway[2799880]: [2024-05-07T22:34:13Z INFO  gateway] closing Ws connection: 127.0.0.1:59320
May 07 22:34:32 Ubuntu-2204-jammy-amd64-base drift-gateway[2799880]: [2024-05-07T22:34:32Z INFO  gateway] closing Ws connection: 127.0.0.1:37914
May 07 22:34:32 Ubuntu-2204-jammy-amd64-base drift-gateway[2799880]: [2024-05-07T22:34:32Z INFO  gateway] accepted Ws connection: 127.0.0.1:37370
May 07 22:34:32 Ubuntu-2204-jammy-amd64-base drift-gateway[2799880]: [2024-05-07T22:34:32Z INFO  gateway] subscribing to events for: 0
May 07 22:35:25 Ubuntu-2204-jammy-amd64-base drift-gateway[2799880]: thread 'main' panicked at src/websocket.rs:74:36:
May 07 22:35:25 Ubuntu-2204-jammy-amd64-base drift-gateway[2799880]: sent: AlreadyClosed
May 07 22:35:32 Ubuntu-2204-jammy-amd64-base drift-gateway[2799880]: [2024-05-07T22:35:32Z WARN  gateway] event stream finished: 0, sending close

**Comment by Borlandini** [comment]
Same problem

**Comment by Borlandini** [comment]
Thank you. It's working.
