### ISSUE TITLE
Gateway crashes on start since Drift v2.82.0 has shipped

### ISSUE THREAD

**Issue by utgarda** [drift-labs/gateway#62]
Using all the settings that previously worked, with the same OS and binaries built earlier, I can't run Gateway now.
* building and running main branch with Rust 1.76.0 - segfaults
* running in Docker - the container stops silently

The only way I was able to run it was altering the provided Dockerfile as follows:
```Dockerfile
FROM rust:1.76.0 as builder

# docker automatically sets this to architecture of the host system
# requires DOCKER_BUILDKIT=1
ARG TARGETARCH

RUN apt-get update && apt-get install -y libgcc1
WORKDIR /build
COPY  . .
#RUN cargo build --release
RUN cargo build
RUN if [ "$TARGETARCH" = "arm64" ]; then \
    cp /lib/aarch64-linux-gnu/libgcc_s.so.1 /build/target/debug/; \
    elif [ "$TARGETARCH" = "amd64" ]; then \
    cp /lib/x86_64-linux-gnu/libgcc_s.so.1 /build/target/debug/; \
    fi

#FROM gcr.io/distroless/base-debian12
FROM debian:12
COPY --from=builder /build/target/debug/libgcc_s.so.1 /lib/
COPY --from=builder /build/target/debug/drift-gateway /bin/drift-gateway
```

**Comment by jordy25519** [comment]
thanks for the report.

it should be resolved in latest release https://github.com/drift-labs/gateway/releases/tag/v0.1.18

re docker issue, need to force the platform to build for x86_64 (have updated readme)

```bash
docker build -f Dockerfile . -t gateway --platform linux/x86_64
```
