### ISSUE TITLE
Verify that a sensible error is returned if user has run out of SOL for gas

### ISSUE THREAD

**Issue by wphan** [drift-labs/gateway#7]
probably a good time to test this case while doing #6 too. There should be a somewhat obscure RPC error like "trying to debit an account without a prior credit" if the signing wallet runs out of SOL (common for bot operators not keeping an eye on their account). A sensible error should be returned in this case

**Comment by jordy25519** [comment]
is this error different for delegated accounts/different fee payer?
during testing the error is either insufficient balance for compute fee or insufficient balance for rent
