### ISSUE TITLE
keypair-pubkey mismatch in delegate signing mode

### ISSUE THREAD

**Issue by utgarda** [drift-labs/gateway#81]
Hi! Can't post orders when using `--delegate`. Checked everything in UI - delegate trading works, tried with 2 different pairs of accounts.

```shell
docker logs gateway-1 
# [2024-10-02T16:38:27Z INFO  gateway] 🏛 gateway listening at http://0.0.0.0:8080
# [2024-10-02T16:38:27Z INFO  gateway] 🪪: authority: A48rDdnMuQicdLfcBiX1NDwRSPRkFQhpMSqbkA7ByFQt, default sub-account: 79QZWZV5BwSkeZvxwx6h4wp6XWm1bFy7u7qk74uw7yrf, 🔑 delegate: 6umx3g7WSshRhtqTfUbqr48jC6EYA1Lc8pRnVqLcTfGh
...
gateway-1  | [2024-10-02T17:39:00Z INFO  gateway] 172.18.0.3 | 500 | POST /v2/orders HTTP/1.1 | (159.115102ms)
gateway-1  | [2024-10-02T17:39:04Z INFO  gateway] 172.18.0.3 | 500 | POST /v2/orders HTTP/1.1 | (161.268423ms)
gateway-1  | [2024-10-02T17:39:47Z INFO  gateway] 172.18.0.3 | 500 | POST /v2/orders HTTP/1.1 | (30001.771049ms)
```

```
INFO - Backing off __place_order(...) for 119.2s (TxNotSentException: {'code': 500, 'reason': 'keypair-pubkey mismatch'})
```

```shell
docker pull ghcr.io/drift-labs/gateway
# Using default tag: latest
# latest: Pulling from drift-labs/gateway
# Digest: sha256:b6f463ea50af5d36771584a59ca48836f4a105c6877cf19a4d4110656a46836a
# Status: Image is up to date for ghcr.io/drift-labs/gateway:latest
```

**Comment by jordy25519** [comment]
I think this is a confusion about the parameters. can you try the following:
```
# this should be the delegate private key
DRIFT_GATEWAY_KEY=<private key of "6umx3g7WSshRhtqTfUbqr48jC6EYA1Lc8pRnVqLcTfGh">
# this is the account pubkey (delegator)
--delegate A48rDdnMuQicdLfcBiX1NDwRSPRkFQhpMSqbkA7ByFQt
```

perharps renaming `--delegate` to `--delegator` or `--authority` may be clearer

**Comment by utgarda** [comment]
Good idea about the naming. Startup logs call them authority and delegate, which is readable enough.
Gateway does not start when authority PK and delegator address don't match. Check this screenshot - these 2 addresses work in Drift web UI
![image](https://github.com/user-attachments/assets/f099853f-adfb-451c-9320-50b439163ae1)

**Comment by jordy25519** [comment]
hmm, it looks like the delegated account is subaccount 1
gateway signs for subaccount 0 by default, may need to set this additional parameter in the query `?subAccountId=1`
e.g. `http://localhost:8080/v1/orders?subAccountId=1`

**Comment by utgarda** [comment]
> `http://localhost:8080/v1/orders?subAccountId=1`
that works, thanks! Should I add `?subAccountId=1` to 
/v2/positions
/v2/positionInfo/{market_id}
and everything else that's acc-specific?

**Comment by jordy25519** [comment]
yup exactly, if its interacting with that subaccount
