### ISSUE TITLE
Allow setting tx priority fee

### ISSUE THREAD

**Issue by jordy25519** [drift-labs/gateway#9]
transaction endpoints should allow receiving a priority fee

**Comment by wphan** [comment]
bumping this as the last couple days have been an absolute nightmare getting transactions to land

the [typescript sdk](https://github.com/drift-labs/protocol-v2/blob/master/sdk/src/priorityFee/priorityFeeSubscriber.ts#L73-L76) polls `getRecentPrioritizationFees` now and auto assigns according to some strategy (avg, max, etc). Might be good to implement that logic in here so users dont have to think about it!
